openapi: "3.0.0"
info:
  title: Leitstand UI Modules API
  description: Access Leitstand UI module descriptors
  version: 0.7.0
  contact:
    name: Martin Steger
    email: martin@rtbrick.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: Module
  description: Leitstand UI module configuration API

paths:
  /ui/modules:
    get:
      tags:
      - Module
      description: Returns a list of deployed modules to render the main menu.
      responses:
        200:
          description: A collection of matching images  
          content:
            application/json:
              schema:
                type: array
                items: 
                   $ref: "#/components/schemas/MainMenuItem"
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/InternalServerError'

  /ui/modules/{module}:
    get:
      tags:
      - Module
      description: Returns the module descriptor for the specified module.
      parameters:
      - in: path
        name: module
        required: true
        schema:
          type: string
          description: The module name.
      responses:
        200:
          description: The settings of the requested image.  
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModuleDescriptor'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          description: The requested module does not exist.
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    InternalServerError:
      description: The server was not able to process the request because of an internal server error, for example if the server cannot connect to the database.
    Unauthorized:
      description: The request does not contain valid authorization data.
  schemas:
    MainMenuItem:
      description: Main menu item of a Leitstand UI menu item.
      type: object
      readOnly: true
      required:
      - module
      - path
      properties:
        module:
          type: string
          description: The module name.
        title:
          type: string
          description: The module title.
        subtitle:
          type: string
          description: The module subtitle.
        label:
          type: string
          description: The module menu item label.
        path:
          type: string
          description: The path to the module welcome page
        position:
          type: string
          description: A hint where to position the main menu item.
          enum:
          - left
          - right
          default: "left"
        roles_allowed:
          type: array
          description: A list of roles allowed to access the module 
          items:
            type: string
    
    ModuleApplication:
      description: Leitstand UI application descriptor
      type: object
      readOnly: true
      required:
      - application
      properties:
        application:
          type: string
          description: The application name
        controller:
          type: string
          description: The controller file name.
          default: "controller.js"
        defer:
          type: boolean
          description: Whether the application resources should be loaded eagerly or on demand.
          default: false
    
    ModuleDescriptor:
      description: Leitstand UI module descriptor
      type: object
      readOnly: true
      required:
      - module
      properties:
        module:
          type: string
          description: the module name
        applications:
          description: List of module applications.
          type: array
          items:
            $ref: "#/components/schemas/ModuleApplication"
        navigation:
          description: The module navigation configuration.
          type: array
          items:
            $ref: "#/components/schemas/ModuleMenu"
    
    ModuleMenu:
      description: Leitstand UI module menu descriptor
      type: object
      readOnly: true
      required:
      - menu
      - items
      properties:
        menu:
          type: string
          description: The menu name.
        label:
          type: string
          description: The menu label.
        title: 
          type: string
          description: The menu title.
        roles_allowed:
          description: Optional array of user roles that are allowed to access this menu.
          items:
            type: string
        requires:
          type: array
          description: Optional array of property names that must be present in the view model to enable this menu.
          items:
            type: string
        view_model:
          type: array
          description: Optional array of property matchers that must be satisfied to enable this menu.
          items:
            $ref: '#/components/schemas/ViewModelPropertyMatcher'
        query:
          type: object
          description: Optional query parameters to be added when selecting a view from the menu.
        items:
          type: array
          description: The menu items.
          items:
            $ref: '#/components/schemas/ModuleMenuItem'
    
    ModuleMenuItem:
      description: Leitstand UI module menu item descriptor
      type: object
      readOnly: true
      required:
      - item
      - view
      properties:
        item: 
          type: string
          description: The name of the menu item.
        label:
          type: string
          description: The label of the menu item.
        title:
          type: string
          description: The title of the menu item.
        view:
          type: string
          description: The path to the view template.
        roles_allowed:
          description: Optional array of user roles that are allowed to access this menu item.
          items:
            type: string    
        requires:
          type: array
          description: Optional array of property names that must be present in the view model to enable this menu.
          items:
            type: string
        view_model:
          type: array
          description: Optional array of property matchers that must be satisfied to enable this menu item.
          items:
            $ref: '#/components/schemas/ViewModelPropertyMatcher'
        query:
          type: object
          description: Optional query parameters to be added when selecting a view from the menu. Overrides conflicting menu query parameters.
   
    ViewModelPropertyMatcher:
      description: A matcher to test the view model in order to enable a menu or menu item
      type: object
      readOnly: true
      required: 
      - property
      properties: 
        property:
          type: string
          description: The view model property name
        exists:
          type: boolean
          description: Indicates whether the property must be present (true) or absent (false).
        matches:
          type: string
          description: A regular expression the property value must match.
        matches_not:
          type: string
          description: A regular expression the property value must not match.
         